* update i82371eb code * add mc146818rtc runtime option code * drop linuxbios_tables.h - its redundant (tables.h) * add subsystem id support * add option_table as a lar file * fix a typo in xconfig * clean up x86emu makefile * add initial support for normal/fallback (incomplete) * add back LBCHKSUM support in linuxbios table
Signed-off-by: Stefan Reinauer <stepan@coresystems.de>
Acked-by: Ronald G. Minnich <rminnich@gmail.com>




git-svn-id: svn://coreboot.org/repository/LinuxBIOSv3@287 f3766cd6-281f-0410-b1cd-43a5c92072e9

diff --git a/util/xcompile/xcompile b/util/xcompile/xcompile
--- a/util/xcompile/xcompile
+++ b/util/xcompile/xcompile
@@ -38,7 +38,7 @@ function searchgnu()
 			fi
 	        fi
 	done
-	echo "ERROR: Missing toolchain: $1" > &3
+	echo "ERROR: Missing toolchain: $1" >&2
 	exit 1
 }
 
