util/xcompile/xcompile: warn when crossgcc is not built
Warn when the default installation directory for crossgcc
(util/crossgcc/xgcc/bin/) is not found.

Change-Id: I1f2a1d29f0d7117d1f80de4af1c24ecedcbea4da
Signed-off-by: Idwer Vollering <vidwer@gmail.com>

diff --git a/util/xcompile/xcompile b/util/xcompile/xcompile
--- a/util/xcompile/xcompile
+++ b/util/xcompile/xcompile
@@ -161,6 +161,10 @@ TCLIST_x86="i386 x86_64"
 TWIDTH_x86="32"
 XGCCPATH=${1:-"`pwd`/util/crossgcc/xgcc/bin/"}
 
+if [ ! -d "$XGCCPATH" ]; then
+	printf "Warning: crossgcc seems to not have been built: can't find ${XGCCPATH}\n" >&2
+fi
+
 # This loops over all supported architectures.
 for architecture in $SUPPORTED_ARCHITECTURE; do
 	GCCPREFIX="invalid"
