gitconfig: Give up commiting when non-ascii character is in commit message.
' ' is 0x20, '~' is 0x7E. The character not between ' ' and '~' could be
treated as non-ascii one, which makes the project less global.

Change-Id: If0bbc4bb6b1f8a0d123d00e2b8e6b29cc78abda0
Signed-off-by: Zheng Bao <zheng.bao@amd.com>
Signed-off-by: Zheng Bao <fishbaozi@gmail.com>

diff --git a/util/gitconfig/commit-msg b/util/gitconfig/commit-msg
--- a/util/gitconfig/commit-msg
+++ b/util/gitconfig/commit-msg
@@ -37,6 +37,12 @@ add_ChangeId() {
 		exit 1
 	fi
 
+	if LANG= grep '[^ -~]' "$MSG" > /dev/null
+	then
+		echo "Aborting commit due to non-ascii characters in commit message."
+		exit 1
+	fi
+
 	# Does Change-Id: already exist? if so, exit (no change).
 	if grep -i '^Change-Id: I[0-9a-f]\{40\}$' "$MSG" >/dev/null
 	then
