gitconfig: Give up commiting if the commit message is empty.
With or without this change, git itself gives up commiting and
prints the same error message.
This just makes the commit-msg take more responsible. It also
helps us how to give up commiting.

Change-Id: I8b6e9eb258dde43776a4d55b4d198b2cc42535f0
Signed-off-by: Zheng Bao <zheng.bao@amd.com>
Signed-off-by: Zheng Bao <fishbaozi@gmail.com>

diff --git a/util/gitconfig/commit-msg b/util/gitconfig/commit-msg
--- a/util/gitconfig/commit-msg
+++ b/util/gitconfig/commit-msg
@@ -33,7 +33,8 @@ add_ChangeId() {
 	' "$MSG" | git stripspace`
 	if test -z "$clean_message"
 	then
-		return
+		echo "Aborting commit due to empty commit message."
+		exit 1
 	fi
 
 	# Does Change-Id: already exist? if so, exit (no change).
