Report build result from abuild (did all requested boards build?)
Signed-off-by: Patrick Georgi <patrick@georgi-clan.de>
Acked-by: Patrick Georgi <patrick@georgi-clan.de>


git-svn-id: svn://svn.coreboot.org/coreboot/trunk@6615 2b7e53f0-3cfb-0310-b3e9-8179ed1497e1

diff --git a/util/abuild/abuild b/util/abuild/abuild
--- a/util/abuild/abuild
+++ b/util/abuild/abuild
@@ -35,6 +35,9 @@ cpus=1
 # Configure-only mode
 configureonly=0
 
+# Did any board fail to build?
+failed=0
+
 # One might want to adjust these in case of cross compiling
 for i in make gmake gnumake nonexistant_make; do
 	$i --version 2>/dev/null |grep "GNU Make" >/dev/null && break
@@ -294,6 +297,7 @@ function compile_target
 		printf "FAILED after ${duration}s!\nLog excerpt:\n"
 		tail -n $CONTEXT make.log 2> /dev/null || tail -$CONTEXT make.log
 		cd $CURR
+		failed=1
 		return 1
 	fi
 }
@@ -622,3 +626,4 @@ else
 fi
 xml '</abuild>'
 
+exit $failed
