These changes get us past stage0, past stage1, and into the search for a file in LAR called raminit.
The intent is that stage0_i586.S would be common for just about all
stage0. It has no includes. We had to go with an ldscript.ld to deal
with the many bugs in binutils. Maybe someday this will change. 

Tested by Ron and Uwe in bochs with debugging. 

Signed-off-by: Ronald G. Minnich <rminnich@gmail.com>
Acked-by: Uwe Hermann <uwe@hermann-uwe.de>


git-svn-id: svn://coreboot.org/repository/LinuxBIOSv3@68 f3766cd6-281f-0410-b1cd-43a5c92072e9

diff --git a/arch/x86/Makefile.target b/arch/x86/Makefile.target
--- a/arch/x86/Makefile.target
+++ b/arch/x86/Makefile.target
@@ -2,6 +2,7 @@
 ## This file is part of the LinuxBIOS project.
 ##
 ## Copyright (C) 2006 coresystems GmbH
+## Copyright (C) 2007 Ron G. Minnich <rminnich@gmail.com>
 ##
 ## This program is free software; you can redistribute it and/or modify
 ## it under the terms of the GNU General Public License as published by
@@ -26,13 +27,13 @@
 
 CFLAGS := 
 
-linuxbios.jump: FORCE
-	$(Q)echo "Building jump vector"
-	$(Q)$(CC) -E $(srctree)/arch/x86/reset.S -o $(objtree)/reset.s -DBOOTBLK=0x1f00 -DRESRVED=0xf0 -DDATE=\"`date +%Y/%m/%d`\"
-	$(Q)$(AS) $(objtree)/reset.s -o $(objtree)/reset.o
-	$(Q)$(LD) -Ttext 0xfffffff0 -s --oformat binary $(objtree)/reset.o -o $(objtree)/linuxbios.jump
-	$(Q)chmod 644 $(objtree)/linuxbios.jump
-	$(Q)echo "Len: `wc -c < linuxbios.jump`"
+#linuxbios.jump: FORCE
+#	$(Q)echo "Building jump vector"
+#	$(Q)$(CC) -E $(srctree)/arch/x86/reset.S -o $(objtree)/reset.s -DBOOTBLK=0x1f00 -DRESRVED=0xf0 -DDATE=\"`date +%Y/%m/%d`\"
+#	$(Q)$(AS) $(objtree)/reset.s -o $(objtree)/reset.o
+#	$(Q)$(LD) -Ttext 0xfffffff0 -s --oformat binary $(objtree)/reset.o -o $(objtree)/linuxbios.jump
+#	$(Q)chmod 644 $(objtree)/linuxbios.jump
+#	$(Q)echo "Len: `wc -c < linuxbios.jump`"
 
 #
 # This part takes care of compression. It should build the compression modules
@@ -92,12 +93,19 @@ linuxbios.lar: $(objtree)/lar lzma linuxbios.initram linuxbios_ram payload
 
 INITCFLAGS=-I$(srctree)/include/cpu/generic/x86 -I$(srctree)/include -fno-builtin -Os
 
-linuxbios.init: 
+# Note: we could cat .o files together, but one important goal is to leave us with a complete gdb-debuggable
+# .o for use with popular ICE and other tools. We go to some effort here to end up with a 
+# stage0.o that has debug symbols. This stage0 will actually load the first LAR file and execute it.
+stage0.init: 
+	echo "You will need to create variables for arch/$(CONFIG_ARCH)"
+	echo "and CC flags for architecture, and to select the stage0_$(CONFIG_STAGE0_1)"
+	echo "these will be set in mainboard Kconfig. Also, you need to define the .c files for "
+	echo "stage0 in that file as well. "
 	$(Q)echo Building linuxbios.init
 	#
 	# asm stub
-	$(Q)$(CC) -E $(srctree)/arch/x86/init.S -o $(objtree)/init.s 
-	$(Q)$(AS) $(objtree)/init.s -o $(objtree)/init.o
+	$(Q)$(CC) -E $(LINUXBIOSINCLUDE) $(srctree)/arch/x86/stage0_i586.S -o $(objtree)/stage0_i586.s -DBOOTBLK=0x1f00 -DRESRVED=0xf0 -DDATE=\"`date +%Y/%m/%d`\"
+	$(Q)$(AS) $(objtree)/stage0_i586.s -o $(objtree)/stage0_i586.o
 	#
 	# main
 	$(Q)$(CC) $(INITCFLAGS) -c $(srctree)/arch/x86/cachemain.c -o cachemain.o
@@ -110,23 +118,28 @@ linuxbios.init:
 	$(Q)$(CC) $(INITCFLAGS) -c $(srctree)/console/vtxprintf.c -o vtxprintf.o
 	$(Q)$(CC) $(INITCFLAGS) -c $(srctree)/lib/uart8250.c -o uart8250.o
 
-	# TODO: dynamic start address 4G - 0x2000 (bootblock size)
-	$(Q)$(LD) -Ttext 0xffffe000 -s --oformat binary init.o cachemain.o console.o uart8250.o \
-		serial.o vtxprintf.o lar.o -o linuxbios.init.pre
+	# leave a .o around for debugging etc.
+	# we did not want to use a ldscript. But the outstanding bugs in gld make it impossible to do 
+	# anything else. 
+	# Google  Not enough room for program headers (allocated 3, need 4)
+	$(Q)$(CC) -m32 -nostdlib -static -T $(srctree)/arch/x86/ldscript.ld cachemain.o console.o uart8250.o \
+		serial.o vtxprintf.o lar.o stage0_i586.o -o stage0.o
+	$(Q)objcopy -O binary stage0.o  stage0.init.pre
 
 	# Pad boot block to 0x2000 - 0x100 
-	$(Q)dd if=linuxbios.init.pre of=linuxbios.init bs=7936 conv=sync
-	$(Q)echo "Len: `wc -c < linuxbios.init.pre`"
+	# we will probably remove this step -- not needed if we continue with ldscript.ld
+	$(Q)dd if=stage0.init.pre of=stage0.init bs=7936 conv=sync
+	$(Q)echo "Len: `wc -c < stage0.init.pre`"
 	#
-	$(Q)test `wc -c < linuxbios.init.pre` -gt 7936  && echo "Error. Bootblock got too big" || true
+	$(Q)test `wc -c < stage0.init.pre` -gt 7936  && echo "Error. Bootblock got too big" || true
 
 #
 # Compose the image:
 #
 	
-linuxbios.rom: linuxbios.lar linuxbios.init linuxbios.vpd linuxbios.jump
-	$(Q)cat $(objtree)/linuxbios.lar $(objtree)/linuxbios.init \
-		$(objtree)/linuxbios.vpd $(objtree)/linuxbios.jump > \
+linuxbios.rom: linuxbios.lar stage0.init linuxbios.vpd 
+	$(Q)cat $(objtree)/linuxbios.lar  \
+		$(objtree)/linuxbios.vpd $(objtree)/stage0.init> \
 		$(objtree)/linuxbios.rom
 
 $(objtree)/lar:
