Get buildgcc to behave reasonably with the -p choice.
buildgcc has many wrong choices, and two right ones,
but you would never guess that. It's even more
frustrating when it spends lots of time building a
full tool chain and you find out it's not the one you
wanted and, still worse, you've forgotten what it does want
and, even worse, it won't f-ing tell you what the two
right choices are!.

Have it tell you when you've done something wrong, and have it
make reasonable decisions when you say things like
-p arm
instead of
-p armv7a-eabi

This change lowers my blood pressure 10 points.

Change-Id: I44a59d7cb7a6260894d8bcb692a693ed25681ff8
Signed-off-by: Ronald G. Minnich <rminnich@gmail.com>

diff --git a/util/crossgcc/buildgcc b/util/crossgcc/buildgcc
--- a/util/crossgcc/buildgcc
+++ b/util/crossgcc/buildgcc
@@ -221,6 +221,16 @@ while true ; do
 	esac
 done
 
+case "$TARGETARCH" in
+	armv7a-eabi)	break;;
+	i386-elf)	break;;
+	i386-mingw32)	break;;
+	i386*)		TARGETARCH=i386-elf;;
+	arm*)		TARGETARCH=armv7a-eabi;;
+	*)		printf "Invalid architecture\n\n"; myhelp; exit 1;;
+esac
+
+echo "Target arch is now $TARGETARCH"
 GDB_PACKAGE="GDB"
 PYTHON_PACKAGE="PYTHON"
 EXPAT_PACKAGE="EXPAT"
