crossgcc: properly test for flex
This is no GNU tool, so testing for "GNU" in the version string
is bound to fail.
We now accept everything that returns success on "flex --version"
and then hope for the best.

I tested both cases

Change-Id: If325f613fde1648847b998b7e8e5782d0f22b484
Signed-off-by: Patrick Georgi <patrick.georgi@secunet.com>
Reviewed-on: http://review.coreboot.org/1884
Tested-by: build bot (Jenkins)
Reviewed-by: Zheng Bao <zheng.bao@amd.com>
Reviewed-by: Stefan Reinauer <stefan.reinauer@coreboot.org>

diff --git a/util/crossgcc/buildgcc b/util/crossgcc/buildgcc
--- a/util/crossgcc/buildgcc
+++ b/util/crossgcc/buildgcc
@@ -119,7 +119,11 @@ MAKE=`searchgnu make` || exit $?
 
 searchgnu m4 > /dev/null
 searchgnu bison > /dev/null
-searchgnu flex > /dev/null
+
+if ! flex --version > /dev/null 2> /dev/null; then
+	printf "${RED}ERROR:${red} Missing toolchain: flex${NC}\n" >&2
+	exit 1
+fi
 
 cleanup()
 {
