util/lint: Update tools that use git to use a library
Each of the tools that used git had similar functionality. This combines
all of that into a single script that gets sourced by each.  This makes
maintenance much easier.

By doing this and updating each of the scripts to do the correct thing
if the script isn't being run in a git repository, it makes them work
much better for the releases, which are just released as a tarball,
without any attached git repository.

Change-Id: I61ba1cc4f7205e0d4baf993588bbc774120405cb
Signed-off-by: Martin Roth <martin@coreboot.org>
Reviewed-on: https://review.coreboot.org/c/coreboot/+/64973
Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Reviewed-by: Elyes Haouas <ehaouas@noos.fr>

diff --git a/util/lint/lint-stable-013-site-local b/util/lint/lint-stable-013-site-local
--- a/util/lint/lint-stable-013-site-local
+++ b/util/lint/lint-stable-013-site-local
@@ -6,14 +6,22 @@
 # Because site-local is intended for local use only, it should never be
 # pushed to coreboot.org.  Even for committing it for local use, it's
 # recommended that it be kept in a separate repository, and pulled in
-# as a git submodule.
+# as a submodule.
 
-LC_ALL=C export LC_ALL
+LINTDIR="$(
+  cd -- "$(dirname "$0")" > /dev/null 2>&1 || return
+  pwd -P
+)"
 
-if [ -n "$(command -v git)" ] && \
-	[ "$(git rev-parse --is-inside-work-tree 2>/dev/null)" = "true" ]
-then
-	if [ -n "$(git ls-files site-local/*)" ]; then
-		echo "Error: site-local must be kept separate from the coreboot repository."
-	fi
+# shellcheck source=helper_functions.sh
+. "${LINTDIR}/helper_functions.sh"
+
+# Exit if the code isn't in a git repo
+if [ "${IN_GIT_TREE}" -eq 0 ]; then
+	exit 0
+fi
+
+
+if [ -n "$(${FIND_FILES} site-local/*)" ]; then
+	echo "Error: site-local must be kept separate from the coreboot repository."
 fi
